tcs_user_parameters:
    path: /{user}/parametres
    defaults:
        _controller: TCSCoreBundle:User:parameters

fos_user_registration:
    path: /register/
    defaults:
        _controller: TCSUserBundle:User:register
