tcs_core:
    resource: "@TCSCoreBundle/Resources/config/routing.yml"
    prefix:   /

tcs_platform:
    resource: "@TCSPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

