
security:
    encoders:
        TCS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_AUTHOR
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: /accueil
                always_use_default_target_path: true
                default_target_path: /accueil
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /accueil
            remember_me:
                secret: "%secret%"
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
