tcs_platform_homepage:
    path:     /accueil
    defaults:
        _controller: TCSCoreBundle:Core:index

tcs_stream:
    path: /stream/{streamer}
    defaults:
        _controller: TCSCoreBundle:Core:stream

