tcs_platform_homepage:
    path:     /accueil
    defaults:
        _controller: TCSPlatformBundle:Article:getLastArticle

tcs_platform_add:
    path: /ajouter-article
    defaults:
        _controller: TCSPlatformBundle:Article:add