tcs_platform_add:
    path: /ajouter-article
    defaults:
        _controller: TCSPlatformBundle:Article:addArticle


tcs_platform_articles:
    path: /articles
    defaults:
        _controller: TCSPlatformBundle:Article:show
